Story4PPW/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/templates/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path('', include('homepage.urls')),
]

homepage/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('more/', views.more, name='more'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('schedule/', views.schedule, name = 'schedule'),
    path('addschedule/', views.addschedule, name = 'addschedule'),
    path('resetAll/',views.resetAll,name = "resetAll"),
]

homepage/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Schedule(models.Model):

    activity = models.CharField(max_length=15)
    description = models.CharField(max_length=40)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=15)
    category = models.CharField(max_length=20)

homepage/forms.py
from django import forms
from .models import Schedule


class scheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity','description', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Schedule
from . import forms


def homepage(request):
    return render(request, 'homepage.html')

def more(request):
    return render(request, 'more.html')

def portfolio(request):
    return render(request, 'portfolio.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def addschedule(request):
    if request.method == 'POST': 
        form = forms.scheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/schedule')

    else:
        form = forms.scheduleForm()
    return render(request, 'addschedule.html', {'form': form})

def resetAll(request):
    Schedule.objects.all().delete()
    schedules =[]
    return render(request, 'schedule.html', {'schedules': schedules})


# Create your views here.

homepage/templates/about.html
{% extends "NavBar.html" %}
{% load static %}
{% block tittle %}About Me | Khansa{% endblock %}
{% block content %}
<title>My Profile</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="bg">
    {% load static %}
    <div class="wrapper">
        <p class="titleabout"> about me.</p>
        <p class="abouttitle"> about me</p>
        <p class="about">
            Hello, I am Khansa Khairunisa Putri. Currently studying at Universitas Indonesia.
            I‘m majoring in Information System, class of 2018.
            I learn about basic languages of programming such as Java and Python.
        </p>
        <p class="about1">
            I'm a creative thinker. I like to explore alternative solutions to problems.
            Also, I really enjoy meeting with new people.
        </p>
        <p class="about2">
            I like watching movie especially action movie.
            Also, I like taking pictures with analog camera,
            because it feels different and unique.
        </p>

        <a href="{% url 'homepage:homepage' %}">
            <img src="{% static 'images/button.png' %}" alt="button" class="more">
            </a>
    </div>

</body>
</html>

homepage/templates/addschedule.html
<!DOCTYPE html>
<html>
	{% load static %}
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
	 <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> 
	 <link rel="stylesheet" type="text/css" href={% static 'style.css' %}> 
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	 <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
	 <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
	 <link rel="stylesheet" href={% static 'js/bootstrap.js' %}>
	 <link rel="stylesheet" href={% static 'js/bootstrap.min.js' %}>
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<head>
	<title>Schedules</title>
</head>
<body>
	<div id="navbar">{% include "navigasi.html" %}</div>
	<div style="padding-left:5%;padding-right:5%;">
        <h1 class="d-flex align-items-center justify-content-center" >Add Schedule</h1>
        {% block content %}
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Submit</button>
        </form>
    {% endblock %}
	</div>
	<br>
	</div>
</body>
</html>

homepage/templates/homepage.html
{% extends "navigasi.html" %}
{% load static %}
{% block tittle %}HOME | Khansa Khairunisa{% endblock %}
{% block content %}
<body style="background-color: #EDEDED">
    <nav class="navbar navbar-expand-lg navbar-light justify-content-center fixed-top" style="background-color: #e5e5e5">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:homepage' %}">HOME</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:more' %}">MORE</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:portfolio' %}">PORTFOLIO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:schedule' %}">SCHEDULE</a>
        </li>
        </ul>
    </nav>
    <br>
    <div class="wrapper d-flex align-items-center justify-content-center">
        <h1 class="homepage"> Hello, I am </h1>
        <br>
        <img src="{% static 'images/homepage.png' %}" alt="homepage" class="homepageimg" style="margin-top: 15vw">
        <!-- <div class="line"></div> -->
    </div>
    
    <!-- <a id="home" href="homepage.html">HOME</a>
    <a id="about" href="about.html">ABOUT</a>
    <a id="contact" href="contact.html">CONTACT</a> -->
    
    </div>
</body>
</html>
{% endblock %}

homepage/templates/more.html
{% extends "navigasi.html" %}
{% load static %}
{% block tittle %}HOME | Khansa Khairunisa{% endblock %}
{% block content %}
<body>
    <br>
    <div style="background-color:#e5e5e5">
        <div class="container-fluid">
        <h1 id="skills">SKILLS</h1>
        
        <div class="row">
            <div class="col">
                <div class="progress" style="margin-top: 130px">
                <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:80%"></div>
                </div><br>
                <p class="skill">Adobe Photoshop</p>

                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:70%"></div>
                </div><br>
                <p class="skill">Adobe Illustrator</p>

                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:80%"></div>
                </div><br>
                <p class="skill">Adobe After Effects</p>
            </div>
            <div class="col">
                <div class="progress" style="margin-top: 130px">
                <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:80%"></div>
                </div><br>
                <p class="skill">Microsoft Word</p>

                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:80%"></div>
                </div><br>
                <p class="skill">Powerpoint</p>

                <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:70%"></div>
                </div><br>
                <p class="skill">Microsoft Excel</p>
            </div>
        </div>
    </div>
    </div>
    </div>
</body>
</html>
{% endblock %}

homepage/templates/navigasi.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{%static 'main.css'%}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="http://draft-online.herokuapp.com/js/jquery.min.js"></script>
    <nav class="navbar navbar-expand-lg navbar-light justify-content-center fixed-top" style="background-color: #e5e5e5">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:homepage' %}">HOME</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:more' %}">MORE</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:portfolio' %}">PORTFOLIO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:schedule' %}">SCHEDULE</a>
            </li>
        </ul>
    </nav>
    <title>{% block tittle %}{% endblock %}</title>
  </head>
  <body>
      {% block content %}{% endblock %}
  </body>
</html>

homepage/templates/portfolio.html
{% extends "navigasi.html" %}
{% load static %}
{% block tittle %}PORTFOLIO | Khansa Khairunisa{% endblock %}
{% block content %}
<body>
  <nav class="navbar navbar-expand-sm justify-content-center fixed-top" style="background-color: #e5e5e5">
    <ul class="navbar-nav">
        <li class="nav-item" style="padding-right: 5rem; padding-left: 8.5rem">
            <a class="nav-link" href="{% url 'homepage:homepage' %}">HOME</a>
        </li>
        <li class="nav-item" style="padding-right: 5rem; padding-left: 8.5rem">
            <a class="nav-link" href="{% url 'homepage:more' %}">MORE</a>
        </li>
        <li class="nav-item" style="padding-right: 5rem; padding-left: 8.5rem">
            <a class="nav-link" href="{% url 'homepage:portfolio' %}">PORTFOLIO</a>
        </li>
    </ul>
    </nav>

    <div id="demo" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ul class="carousel-indicators">
          <li data-target="#demo" data-slide-to="0" class="active"></li>
          <li data-target="#demo" data-slide-to="1"></li>
          <li data-target="#demo" data-slide-to="2"></li>
          <li data-target="#demo" data-slide-to="3"></li>
          <li data-target="#demo" data-slide-to="4"></li>
          <li data-target="#demo" data-slide-to="5"></li>
        </ul>
        
        <!-- The slideshow -->
        <div class="carousel-inner">
          <div class="carousel-item active">
              
            <img src="{% static 'images/6.png' %}" alt="title">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/2.png' %}" alt="1">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/4.png' %}" alt="2">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/3.png' %}" alt="3">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/1.png' %}" alt="4">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/5.png' %}" alt="5">
          </div>
        </div>
        
        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
          <span class="carousel-control-next-icon"></span>
        </a>
      </div>
</body>
</html>
{% endblock %}

homepage/templates/schedule.html
<!DOCTYPE html>
<html>
	{% load static %}
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
	 <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> 
	 <link rel="stylesheet" type="text/css" href={% static 'style.css' %}> 
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	 <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
	 <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
	 <link rel="stylesheet" href={% static 'js/bootstrap.js' %}>
	 <link rel="stylesheet" href={% static 'js/bootstrap.min.js' %}>
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<head>
	<title>Create Schedule</title>
</head>
<body>
	<div id="navbar">{% include "navigasi.html" %}</div>
	{% block content %}
    <h1 class="d-flex align-items-center justify-content-center">My Schedule</h1>
    <div class="article">
        <div class="d-flex align-items-center justify-content-center">
            <a href="{% url 'homepage:addschedule' %}"><button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-pencil"></span> Add Schedule
                </button></a>
            <a href="{% url 'homepage:resetAll' %}">
                <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash"></span> Reset Data
                </button></a>
        </div>
        <div class="article">
            <div class="row">
                {% for schedule in schedules %}
                    <div class="col-sm-4 text-center">
                        <h2 class="act">{{ schedule.activity }}</h2>
                        <h3 class="desc">{{ schedule.description }}</h3>
                        <p>{{ schedule.date.date }}<br>
                            {{ schedule.time}}<br>
                            {{ schedule.place }}<br>
                            {{ schedule.category }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>